# Generated by Django 5.2.11 on 2026-02-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('heure', models.TimeField()),
                ('date', models.DateField()),
                ('rappel', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('a_faire', 'à faire'), ('en__cours', 'en cours'), ('termine', 'terminé')], default='a_faire', max_length=50)),
            ],
        ),
    ]
